import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/one_dark.toml"
]

[scrolling]
history = 100000

[env]
# term = "xterm-256color"

[font]
size = 12

